GET http://localhost:3001/api/persons

###

GET http://localhost:3001/info

###
GET http://localhost:3001/api/persons/10

###
DELETE http://localhost:3001/api/persons/523995

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "id": "",
    "name": "Mary Popk", 
    "number": "39-212123"
}


//Testing with render
###
GET https://part3-phonebook-backend-bh2t.onrender.com/api/persons

###

GET https://part3-phonebook-backend-bh2t.onrender.com/info

###
GET https://part3-phonebook-backend-bh2t.onrender.com/api/persons/10

###
DELETE https://part3-phonebook-backend-bh2t.onrender.com/api/persons/411208

###
POST https://part3-phonebook-backend-bh2t.onrender.com/api/persons
Content-Type: application/json

{
    "id": "",
    "name": "Mary Popk", 
    "number": "39-212123"
}
